# Generated by Django 5.1.3 on 2024-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sweet_word',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
