# Generated by Django 5.1.3 on 2024-11-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_user_sweet_word_user_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_email', models.EmailField(max_length=254, unique=True)),
                ('session_token', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.user')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
